### ISSUE TITLE
Loss of perfomance after X number of items in dict?

### ISSUE THREAD

**Issue by johny-bravo** [honzajavorek/redis-collections#106]
I run the following code

    con = redis.StrictRedis(host='localhost', port=6379, db=0)

    writes = [
        10,
        100,
        1000,
        10000,
        100000,
        1000000,
        100000,
        10000,
        1000,
        100,
        10,
    ]

    def test(c, w):
        t = time.time()
        data = SyncableDict(key='test', redis=c, writeback=True)

        with data as d:
            for i in range(w):
                d[i] = 'test%d' % i
        print 'writes: %7d time:   %8f' % (w, time.time() - t)

    for wr in writes:
        test(con, wr)

and get following stats:
```
writes:      10 time:   1.0080
writes:     100 time:   0.0050
writes:    1000 time:   0.0360
writes:   10000 time:   0.3300
writes:  100000 time:   3.3900
writes: 1000000 time:   34.9170
writes:  100000 time:   2.1360
writes:   10000 time:   14.4460
writes:    1000 time:   14.6300
writes:     100 time:   14.4970
writes:      10 time:   14.5950
```
if i run the code again against the same key `test`, i get the following stats:
```
writes:      10 time:   15.7820
writes:     100 time:   14.7450
writes:    1000 time:   14.7040
writes:   10000 time:   14.7170
writes:  100000 time:   14.7690
writes: 1000000 time:   35.4770
writes:  100000 time:   2.1710
writes:   10000 time:   14.7980
writes:    1000 time:   14.7320
writes:     100 time:   14.8530
writes:      10 time:   14.7780
```
i get same speeds with .get() after there's ~1m keys in SyncableDict
i guess after a certain amount of key:val in SyncableDict, its perfomance deteriorates?
when i try to write 10m, python's mem usage goes into gigabytes and it never finishes
is there a limit on number of keys or am i doing it wrong?
my python ver is `Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32`

**Comment by bbayles** [comment]
Thanks for writing. I think the performance of the SyncableDict is fine while it's in the `with` block - you can add, retrieve, and remove items just fine. The slowdown seems to come when the block exits and the dict syncs back to Redis.

In that case all of the items have to be pickled, which is somewhat slow, and also written to Redis. We use `hmset` to put all of the data through to Redis in one command, but that does increase the memory usage.

I will experiment with some optimizations to the sync process to see if it can be made more friendly.

**Comment by whynot123** [comment]
thanks a lot! 
syncing seems to take a lot of time even for small number of sets/gets once SyncableDict reaches certain size. 
should i go with multiple SyncableDict objects and share one connection between them if i want to store lots of items and not get hit with long sync times?

**Comment by bbayles** [comment]
Not sure if you intend this to be the test, but since your code attaches to the `test` key in each run, the size of the collection stored in Redis goes from 10, 100, 1000000 and then stays at 1000000. So the first 10 is "insert into a collection with 0 items" and the second is "insert into a collection with 1000000 items."

**Comment by whynot123** [comment]
in my application i have multiple python processes that `.get()` and `.set()` dicts from redis server,
processes need to see changes immediately after the key is set/changed

so i serialize/deserialize data with `json` module, which takes 
```
max time 1.078 sec per 1 .set()
total time 77.0099 sec for 1000000 .set()'s 
```
when i run the same test with `SyncableDict` (each dict object has different `key`), i get 
```
max time 0.0019 sec per 1 .set() 
total time: 85.6929 sec for 1000000 .set()'s 
```
if i don't call `.sync()` after each `.set()` (this way processes won't see changes) 
and if i call `.sync()` it takes a lot of time:
```
total time: 417.9920 sec for 1000000 .set()'s
```
so is there a better way to implement this with `SyncableDict` or should i stick to `json`?

**Comment by bbayles** [comment]
What sort of items are you storing in Redis? If they're not mutable things like dicts of lists or dicts of dicts you could use `redis_collections.Dict` with `writeback=False` instead of `SyncableDict`. Changes would be reflected in Redis immediately (see [example](http://redis-collections.readthedocs.io/en/stable/basic-usage.html#id1)).

I made PR #107 to help with some memory issues during `Dict.update`.

**Comment by whynot123** [comment]
hey, thx for the PR!
i store dicts with occasional lists of tuples inside them

**Comment by domface** [comment]
@johny-bravo how did you swap out pickle for json as your serializer?

**Comment by johny-bravo** [comment]
@domface i ended up using plain json with `.dumps`/`.reads` without redis-collections

**Comment by bbayles** [comment]
I'll close out this issue. To future people reading this, note that the test in the OP isn't quite measuring what it says - see [here](https://github.com/honzajavorek/redis-collections/issues/106#issuecomment-269220976).
