### ISSUE TITLE
Redis Cluster Support

### ISSUE THREAD

**Issue by domface** [honzajavorek/redis-collections#109]
Opening a ticket for providing Redis cluster support. Will work on this in the meantime.

**Comment by bbayles** [comment]
I presume you mean via the [redis-py-cluster](https://redis-py-cluster.readthedocs.io/en/master/) package?

**Comment by domface** [comment]
Yes that's correct.

**Comment by bbayles** [comment]
Ah. So, this will _sort_ of work for basic things, but fail for lots of other things.

```python
>>> rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=False)
>>> L = List(redis=rc)
>>> L.append(b'1')
>>> L.append(b'2')
>>> L
<redis_collections.List at c6af25fb03ac4fb1ad4408ee3f29f456 [b'1', b'2']>  # Works!
>>> L.extend([b'3', b'4'])
Traceback (most recent call last):
...
rediscluster.exceptions.RedisClusterException: method StrictRedisCluster.transaction() is not implemented
```

As you can see, the `redis-py-cluster` library [doesn't support transactions](http://redis-py-cluster.readthedocs.io/en/master/pipelines.html#transactions-and-watch). Unfortunately, `redis-collections` uses transactions extensively, and I'm not inclined to re-write the library without them (losing their guarantees).

If `redis-py-cluster` does implement transactions, this library would need to make sure to only create keys with a particular hash tag (see [here](https://redis.io/topics/cluster-tutorial#migrating-to-redis-cluster)). I'd be inclined to implement that.

Hope that helps!
