### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by waprin** [honzajavorek/redis-collections#122]
Hi - is there an easy way to serialize data using JSON instead of pickle? One major motivation for this is pickle includes classnames which broke some stuff when I moved a file.

If it's not supported, any thoughts on difficulty adding? If I wrote a PR, would the repo owners be willing to merge it and make it part of the official package?

Thanks.

**Comment by bbayles** [comment]
This library doesn't serialize with JSON, but as the docs note:
> If you don’t like how pickle does serialization, you may override the _pickle* and _unpickle* methods on the collection classes. Using other serializers will limit the objects you can store or retrieve.

```python
import json

from redis_collections import Dict


class JSONDict(Dict):
    _pickle_key = staticmethod(json.dumps)
    _unpickle_key = staticmethod(json.loads)
    _pickle_value = staticmethod(json.dumps)


with JSONDict() as d:
    d['a'] = 1
    print(d['a'])
    d['a'] = 2
    print(d['a'])
```

**Comment by waprin** [comment]
@bbayles thanks!
