### ISSUE TITLE
Defaultdict support?

### ISSUE THREAD

**Issue by waprin** [honzajavorek/redis-collections#123]
Similar line of questions to #112 - does this library have any ideas for supporting defaultdict? If I added it would owners be willing to merge a PR and make it official? Thanks.

**Comment by bbayles** [comment]
Good news - `DefaultDict` already exists.

See [the docs](https://redis-collections.readthedocs.io/en/stable/api.html#redis_collections.dicts.DefaultDict) for information.

```python
from redis_collections import DefaultDict

with DefaultDict(list) as d:
    d['a'].append(1)
    d['a'].append(2)
```
