### ISSUE TITLE
version missmatch with redis

### ISSUE THREAD

**Issue by leifj** [honzajavorek/redis-collections#127]
version 0.7.1 has the following requirement on redis:

redis<3.4.0,>=3.1.0

Since redis is currently at 3.4.1 this breaks builds.

**Comment by bbayles** [comment]
Version 0.7.1 is not compatible with Redis 3.4.0 or 3.4.1. So the restriction is correct.

I'll release version 0.8.0 soon, which will be.

**Comment by bbayles** [comment]
The new version is out - please do report any bugs with redis-py 3.4.x.
