### ISSUE TITLE
synchronization among multiple instances

### ISSUE THREAD

**Issue by qpxu007** [honzajavorek/redis-collections#132]
Not a bug, but a feature request. 

Assume two instances (A and B) running

A:
 
L = List(key=, redis=)

B:
L = List(key=, redis=)

If A is updated and sync'ed to redis, the B instance will not update, and it can be updated with reinitialization

L= List(key=, redis=)
 
Is there an easier way to achieve this? e.g. with a function, 

L.sync_from_db()

def sync_from_db(self):
      return self.__init__(key=self.key, redis=self.redis)

I feel that the functional form is easier to read/understand and more concise syntax wise. Thanks

**Comment by bbayles** [comment]
Hmm, not sure I follow.

```python
# Session 1
from redis_collections import List
L_1 = List(key='17170fb9fbd44cfa960ed2c81e58d671')
L_1.extend([1, 2, 3])
```

```python
# Session 2
from redis_collections import List
L_2 = List(key='17170fb9fbd44cfa960ed2c81e58d671')
```

```python
# Session 1 again
L_1.append(4)
```

```python
# Session 2 again
list(L_2)
```

I get `[1, 2, 3, 4]` as the output - no re-initialization needed. Am I missing something?

**Comment by qpxu007** [comment]
I tried with SyncableList, I assumed it has the same behavior as List, but apparently not?

# Session 1

from redis_collections import SyncableList
L_1 = SyncableList(key='17170fb9fbd44cfa960ed2c81e58d671')

# Session 2

from redis_collections import SyncableList
L_1 = SyncableList(key='17170fb9fbd44cfa960ed2c81e58d671')

# Session 1:
L_1.extend([1, 2, 3])
L_1.sync()
L_1 
[1,2,3]

#Session 2:
L_1
[]

**Comment by bbayles** [comment]
To do it with `SyncableList`, use slice assignment:

```
# In session 2
L_2[:] = L2_.persistence
```

**Comment by qpxu007** [comment]
Great, thanks
