### ISSUE TITLE
Suggest testing against standard objects

### ISSUE THREAD

**Issue by doc-hex** [honzajavorek/redis-collections#28]
The tests could be generalized and improved if they tested themselves against the standard (non-redis) implementations of these objects.

For example, the `List` class should operate the same as build-in `list` class, at least for all operations it supports. So if the same members are called with the same arguments, the results should be the same.

This would have exposed the bugs in `List.insert` implementation, [fixed in recent pull](https://github.com/honzajavorek/redis-collections/pull/27).

**Comment by bbayles** [comment]
This is next on my list. `List` class has several slicing bugs that are revealed by doing this! `L[start:stop:slice]` is surprisingly not the same as `L[start:stop][::slice]`.
