### ISSUE TITLE
Find maintainers

### ISSUE THREAD

**Issue by honzajavorek** [honzajavorek/redis-collections#33]
I don't have time (motivation) currently to maintain `redis-collections` much (not even for PR reviews, which is pretty sad) and I'm looking for a maintainer. It wouldn't be much hassle as there are just minor bugs with existing PRs and the only major feature is Python 3 support and it also has a PR in progress. If anyone feels like taking over this library, it would be much appreciated.

**Comment by honzajavorek** [comment]
@bbayles wrote me he's willing to help me with maintaining this library! 🎉 I'll add him to this repository. Before closing this issue, we should see:

- [ ] @bbayles added to repo
- [ ] @bbayles added to PyPI or automatic releasing set up on Travis CI
- [ ] @bbayles fixing/merging something and releasing a new version to PyPI to confirm everything works

**Comment by bbayles** [comment]
Excellent! I'm @bbayles on RTD now. I'll be looking at merging PRs when I return from travel tomorrow.

**Comment by honzajavorek** [comment]
@bbayles Added you. Great, thanks!

**Comment by bbayles** [comment]
The fixes for the issues in #29 and #32 are [on PyPI](https://pypi.python.org/pypi/redis-collections/0.1.8). I missed the version bump when I first tagged the release, but it looks like I got that sorted out.

Publishing via Travis CI is good, but perhaps you could also add me to the project on PyPI?

**Comment by honzajavorek** [comment]
Added! 🎈
