### ISSUE TITLE
I'm working on the same idea...

### ISSUE THREAD

**Issue by brainix** [honzajavorek/redis-collections#34]
Hello, folks!

I just now found Redis Collections, which is crazy, because I'm working on the same idea.  I call my package [Pottery](https://github.com/brainix/pottery).  I see that you support Python 2.6+, while I'm focused on Python 3.4+.  You had this idea first, but I came up with it independently.  Is there any way for us to collaborate?

Thanks, and keep up the great work!
Raj

**Comment by honzajavorek** [comment]
Hi Raj,

I would really appreciate if you could join me in working on this library. It has users, it has pending Pull Requests with work to be just reviewed and merged... even one for adding Python 3 support. I struggle to find time to review. I am not having so much time to maintain this as I would wish, but the library still works with a few glitches and it could help people, so I'm not willing to say it's obsolete or something. It could just use some love from a maintainer, probably just 1 hour per week, and it would soon be shiny and awesome again. What do you think?

Honza

**Comment by honzajavorek** [comment]
Regarding Pottery, if you won't like joining `redis_collections`, I'd suggest to take as much code from this project as you want (just keep the license / attribution) and declare this project as obsolete in favor of your Pottery.

**Comment by honzajavorek** [comment]
Since I didn't hear from @brainix and there's update on #33, I'm closing this.
