### ISSUE TITLE
Employ all good advices from PyPA

### ISSUE THREAD

**Issue by honzajavorek** [honzajavorek/redis-collections#39]
Read http://python-packaging-user-guide.readthedocs.io/ and employ all good modern practices written there.

Also: https://caremad.io/2013/07/setup-vs-requirement/

**Comment by bbayles** [comment]
Below is a checklist for the recommendations in the PyPA guide. I'll tick off the ones that are already satisfied and make PRs for the rest before the 1.0 release.

---

Initial Files
- [ ] setup.py
- [ ] setup.cfg
- [ ] README.rst
- [ ] MANIFEST.in

setup() args
- [ ] name
- [ ] version
- [ ] description
- [ ] url
- [ ] author
- [ ] license
- [ ] classifiers
- [ ] keywords
- [ ] packages
- [ ] install_requires
- [ ] package_data
- [ ] data_files
- [ ] scripts
- [ ] entry_points

Choosing a versioning scheme
- [ ] Semantic, Date based, serial, hybrid?

Packaging
- [ ] Source distribution
- [ ] Wheels - universal? platform?

Others:
- [ ] Single-sourcing the Project Version

**Comment by bbayles** [comment]
Closing; recent changes should fix!

I think the requirements/setup.py method in the OP doesn't really buy this library much, as our dependency list is pretty manageable. I might change my mind if an external library breaks things, but I also might want to know about that from Travis...

**Comment by honzajavorek** [comment]
👍 great!
