### ISSUE TITLE
0.3.0 release plan

### ISSUE THREAD

**Issue by bbayles** [honzajavorek/redis-collections#59]
My plan for the next release:
* Since it will involve breaking changes, it will be 0.3.0
* Work will be done on the [0.3.0 branch](https://github.com/honzajavorek/redis-collections/tree/0.3.0). PRs targeting the 0.3.0 issues will be merged into that branch
* Once it's time for a release the 0.3.0 branch will be merged into master

Also:
* Bug fixes for 0.2.x will be merged into master and released to PyPI until 0.3.0 is ready.
* After 0.3.0 is out bug fixes will go into 0.3.x releases
* The next release with breaking changes will be 0.4.0
* At some point we may call a release "1.0" - after that we'll use semantic versioning - major version increments for breaking changes, minor version increments for backward-compatible additions, and patch version increments for bug fixes.

**Comment by bbayles** [comment]
PR #70 for issue #60 is the last issue I'm targeting for 0.3.0. I plan on checking over docs again and doing a release this weekend. @honzajavorek, anything you'd like to see before that?

**Comment by honzajavorek** [comment]
I'm okay with this plan!

I have no further suggestions for 0.3.0.

I guess a nice requirement for 1.0.0 would be to have a full test coverage for both redis collections and their native counterparts as in #28. Also verifying we don't miss anything suggested by #39 would be nice.

Regarding semantic versioning, recently I became quite a fan of [semantic release](https://github.com/semantic-release/semantic-release) - in Python it's implemented as [python-semantic-release](https://github.com/relekang/python-semantic-release). I won't push it, especially when it's not so adopted in the Python world, but check it out. [I was pretty reserved](https://github.com/apiaryio/dredd/issues/438#issuecomment-208437527) when learning about it, but I gave it a try and now I'm pretty convinced it's useful. For me as a maintainer it's very addictive.
